# Generated by config_brpc.sh, don't modify manually
HDRS=/usr/local/include/
LIBS=/usr/local/lib
PROTOC=/usr/local/bin/protoc
PROTOBUF_HDR=/usr/local/include/
CC=gcc
CXX=g++
GCC_VERSION=50200
STATIC_LINKINGS= -lgflags -lprotobuf
DYNAMIC_LINKINGS=-lpthread -lrt -lssl -lcrypto -ldl -lz -lleveldb
ifeq ($(NEED_LIBPROTOC), 1)
    STATIC_LINKINGS+=-lprotoc
endif
ifeq ($(NEED_GPERFTOOLS), 1)
    $(error "Fail to find gperftools")
endif
CPPFLAGS+=-DBRPC_WITH_GLOG=0 -DGFLAGS_NS=google -g
ifeq ($(NEED_GTEST), 1)
    $(error "Fail to find gtest")
endif
